version: '3'
services:
  go_host:
    build: .
    container_name: "go_host"
    tty: true
    stdin_open: true
    command: /bin/bash
    #ホストのディレクトリをコンテナにマウント
    volumes:
      - .:/go/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      # ssh でgitなどをしたい場合設定を置くと良い
      # - ./env/.ssh:/root/.ssh